// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/api/post.ts";
import * as $1 from "./routes/api/sse.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Canvas.tsx";
import * as $$1 from "./islands/Die.tsx";
import * as $$2 from "./islands/InfoLabel.tsx";
import * as $$3 from "./islands/LeftScores.tsx";
import * as $$4 from "./islands/Popup.tsx";
import * as $$5 from "./islands/ScoreButton.tsx";
import * as $$6 from "./islands/Scores.tsx";
import * as $$7 from "./islands/Sounds.tsx";
import * as $$8 from "./islands/ViewController.tsx";

const manifest = {
  routes: {
    "./routes/api/post.ts": $0,
    "./routes/api/sse.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Canvas.tsx": $$0,
    "./islands/Die.tsx": $$1,
    "./islands/InfoLabel.tsx": $$2,
    "./islands/LeftScores.tsx": $$3,
    "./islands/Popup.tsx": $$4,
    "./islands/ScoreButton.tsx": $$5,
    "./islands/Scores.tsx": $$6,
    "./islands/Sounds.tsx": $$7,
    "./islands/ViewController.tsx": $$8,
  },
  baseUrl: import.meta.url,
};

export default manifest;
